### ISSUE TITLE
Gradle sync failed: Connection timed out: connect

### ISSUE THREAD

**Issue by jamilxt** [laxmimerit/Real-Time-Accelerometer-Data-Plot#1]
Those are who are having this issue: 
remove or comment out the these proxy settings from **gradle.properties**.

```
systemProp.https.proxyPort=8080
systemProp.http.proxyHost=172.16.2.30
org.gradle.jvmargs=-Xmx1536m
systemProp.https.proxyHost=172.16.2.30
systemProp.http.proxyPort=8080
```

**Comment by prof-kalabwa** [comment]
Don't have these on gradle.properties 

Any suggestions to solve this?

**Comment by laxmimerit** [comment]
Check it now. @jamilxt Thanks for merging.

**Comment by jamilxt** [comment]
> Don't have these on gradle.properties
> 
> Any suggestions to solve this?

@prof-kalabwa Hi, kindly, clone the latest project. I hope, you won't face any issue now. Let us know if you are. 

@laxmimerit  Thank you so much for merging. ^_^
